// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LexisNexis.Red.iOS
{
	public partial class LNWebTagEditViewController : UIViewController
	{
		public LNWebTagEditViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
