// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LexisNexis.Red.iOS
{
	public partial class LNWebCollectionViewController : UICollectionViewController
	{
		public LNWebCollectionViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
