// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace LexisNexis.Red.iOS
{
	public partial class ColorCollectionViewCell : UICollectionViewCell
	{
		public ColorCollectionViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
