//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexisNexis.Red.Common.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LexisNexis.Red.Common.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///&lt;p&gt; &lt;span  style=&quot;font-size:15px;font-weight:bold;color:red;&quot;&gt;&amp;#183;Subscription Expired&lt;/span&gt;&amp;nbsp; &amp;nbsp; 
        ///&lt;span style=&quot;font-size:13px;font-weight:bold;&quot;&gt;Contact 1800 772 or&lt;/span&gt;&amp;nbsp;
        ///&lt;a  style=&quot;font-size:13px;color:#3a8efa;&quot; href=&quot;mailto:customersupport@lexisnexis.com.au&quot;&gt;customersupport@lexisnexis.com.au&lt;/a&gt;&lt;/p&gt;
        ///&lt;span style=&quot;color:#9f9f9f;&quot;&gt;
        ///We would like to thank you for choosing LexisNexis to support the great work you do on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AU_ExpiryNotification {
            get {
                return ResourceManager.GetString("AU_ExpiryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///&lt;p&gt; &lt;span  style=&quot;font-size:15px;font-weight:bold;color:red;&quot;&gt;&amp;#183;Subscription Expired&lt;/span&gt;&amp;nbsp; &amp;nbsp; 
        ///&lt;span style=&quot;font-size:13px;font-weight:bold;&quot;&gt;Contact 1800 772 or&lt;/span&gt;&amp;nbsp;
        ///&lt;a  style=&quot;font-size:13px;color:#3a8efa;&quot; href=&quot;mailto:customersupport@lexisnexis.com.hk&quot;&gt;customersupport@lexisnexis.com.hk&lt;/a&gt;&lt;/p&gt;
        ///&lt;span style=&quot;color:#9f9f9f;&quot;&gt;
        ///We would like to thank you for choosing LexisNexis to support the great work you do on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HK_ExpiryNotification {
            get {
                return ResourceManager.GetString("HK_ExpiryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        /// ul {list-style:none;margin:0px;padding:0px;} 
        /// .mbold
        /// {
        /// font-weight:bold;
        /// }.mred
        /// {
        /// color:blue;} h3
        /// {
        ///color:#000000;
        ///font-size:15px;
        ///line-height:20px;
        ///font-weight:normal;
        /// }
        ///body
        ///{
        ///color:#000000;
        ///font-size:12px;
        ///line-height:16px;
        ///font-weight:normal;
        ///}
        ///&lt;/style&gt;&lt;!--#Style#--&gt;
        /// &lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h3&gt;
        ///LexisNexis Legal &amp; Professional 
        ///&lt;/h3&gt;
        ///&lt;p&gt;
        /// &lt;a href=&quot;http://www.lexisnexis.com&quot; class=&quot;mred&quot;&gt; www.lexisnexis.com&lt;/a&gt;   is a leading global provider of content [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LNInfo {
            get {
                return ResourceManager.GetString("LNInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        /// ul
        /// {
        /// list-style-type:disc;
        /// margin:0px;
        /// } 
        /// .mbold
        /// {
        /// font-weight:bold;
        /// }
        /// .small
        /// {
        /// font-size:small;color:gray;}
        ///&lt;/style&gt;&lt;!--#Style#--&gt;
        /// &lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;h3&gt;LexisNexis RedInfo &lt;/h3&gt;
        ///&lt;!--#SyncTime#--&gt;
        ///&lt;p&gt;
        ///LexisNexis Red is a mobile referencing solution providing you with access to your digital library via your iPad or laptop. LexisNexis Red was designed based on customer feedback with the needs of the Legal Practitioner in mind. LexisNexis Red provides:
        ///&lt;/p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LNRedInfo {
            get {
                return ResourceManager.GetString("LNRedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///&lt;p&gt; &lt;span  style=&quot;font-size:15px;font-weight:bold;color:red;&quot;&gt;&amp;#183;Subscription Expired&lt;/span&gt;&amp;nbsp; &amp;nbsp; 
        ///&lt;span style=&quot;font-size:13px;font-weight:bold;&quot;&gt;Contact 1800 772 or&lt;/span&gt;&amp;nbsp;
        ///&lt;a  style=&quot;font-size:13px;color:#3a8efa;&quot; href=&quot;mailto:customersupport@lexisnexis.com.my&quot;&gt;customersupport@lexisnexis.com.my&lt;/a&gt;&lt;/p&gt;
        ///&lt;span style=&quot;color:#9f9f9f;&quot;&gt;
        ///We would like to thank you for choosing LexisNexis to support the great work you do on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MY_ExpiryNotification {
            get {
                return ResourceManager.GetString("MY_ExpiryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///&lt;p&gt; &lt;span  style=&quot;font-size:15px;font-weight:bold;color:red;&quot;&gt;&amp;#183;Subscription Expired&lt;/span&gt;&amp;nbsp; &amp;nbsp; 
        ///&lt;span style=&quot;font-size:13px;font-weight:bold;&quot;&gt;Contact 1800 772 or&lt;/span&gt;&amp;nbsp;
        ///&lt;a  style=&quot;font-size:13px;color:#3a8efa;&quot; href=&quot;mailto:customersupport@lexisnexis.com.nz&quot;&gt;customersupport@lexisnexis.com.nz&lt;/a&gt;&lt;/p&gt;
        ///&lt;span style=&quot;color:#9f9f9f;&quot;&gt;
        ///We would like to thank you for choosing LexisNexis to support the great work you do on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NZ_ExpiryNotification {
            get {
                return ResourceManager.GetString("NZ_ExpiryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///    &lt;/head&gt;
        ///    &lt;body&gt;
        ///&lt;p&gt; &lt;span  style=&quot;font-size:15px;font-weight:bold;color:red;&quot;&gt;&amp;#183;Subscription Expired&lt;/span&gt;&amp;nbsp; &amp;nbsp; 
        ///&lt;span style=&quot;font-size:13px;font-weight:bold;&quot;&gt;Contact 1800 772 or&lt;/span&gt;&amp;nbsp;
        ///&lt;a  style=&quot;font-size:13px;color:#3a8efa;&quot; href=&quot;mailto:customersupport@lexisnexis.com.sg&quot;&gt;customersupport@lexisnexis.com.sg&lt;/a&gt;&lt;/p&gt;
        ///&lt;span style=&quot;color:#9f9f9f;&quot;&gt;
        ///We would like to thank you for choosing LexisNexis to support the great work you do on [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SG_ExpiryNotification {
            get {
                return ResourceManager.GetString("SG_ExpiryNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        /// ul {list-style:none;margin:0px;padding:0px;} 
        /// .mbold
        /// {
        /// font-weight:bold;
        /// }h3
        /// {
        ///color:#000000;
        ///font-size:15px;
        ///line-height:20px;
        ///font-weight:normal;
        /// }
        ///body
        ///{
        ///color:#000000;
        ///font-size:12px;
        ///line-height:16px;
        ///font-weight:normal;
        ///}
        ///&lt;/style&gt;&lt;!--#Style#--&gt;
        /// &lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;center&gt;
        ///&lt;h3&gt;
        ///LICENSED APPLICATION END USER LICENSE AGREEMENT (&amp;ldquo;Agreement&amp;rdquo;) 
        ///&lt;/h3&gt;
        ///&lt;/center&gt;
        ///
        ///&lt;p&gt;
        ///WHEREAS:
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///You (&lt;span class=&quot;mbold&quot;&gt;the individual or entity acce [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
    }
}
